//
//  Metadata
//
//  Generated by JSON Model Generator v0.0.3 on Thu Feb 19 21:20:03 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

package com.intere.generator.metadata;

import java.util.List;
import java.util.ArrayList;
import java.util.Date;
import java.io.Serializable;


@SuppressWarnings("serial")
public class Metadata implements Serializable {
	private String language;
	private String namespace;
	private List<MetadataClasses> classes = new ArrayList<MetadataClasses>();
	private MetadataGenerate generate;

	/**
	 * Setter for language property.
	 */
	public void setLanguage(String language) {
		this.language = language;
	}

	/**
	 * Getter for language property.
	 */
	public String getLanguage() {
		return language;
	}

	/**
	 * Setter for namespace property.
	 */
	public void setNamespace(String namespace) {
		this.namespace = namespace;
	}

	/**
	 * Getter for namespace property.
	 */
	public String getNamespace() {
		return namespace;
	}

	/**
	 * Setter for classes property.
	 */
	public void setClasses(List<MetadataClasses> classes) {
		this.classes = classes;
	}

	/**
	 * Getter for classes property.
	 */
	public List<MetadataClasses> getClasses() {
		return classes;
	}

	/**
	 * Setter for generate property.
	 */
	public void setGenerate(MetadataGenerate generate) {
		this.generate = generate;
	}

	/**
	 * Getter for generate property.
	 */
	public MetadataGenerate getGenerate() {
		return generate;
	}

}
