package com.intere.generator.metadata;

/**
 * MetadataGenerate.java
 * 
 * Generated by JSON Model Generator v0.0.4 on Tue Mar 31 08:38:11 MDT 2015.
 * https://github.com/intere/generator-json-models
 * 
 * The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
*/

import java.io.Serializable;

@SuppressWarnings("serial")
public class MetadataGenerate implements Serializable {
	private Boolean models;
	private Boolean tests;
	private Boolean views;
	private Boolean services;
	private Boolean restServices;

	/**
	 * Setter for models property
	*/
	public void setModels(Boolean models) {
		this.models = models;
	}

	/**
	 * Getter for models property
	*/
	public Boolean getModels() {
		return this.models;
	}

	/**
	 * Setter for tests property
	*/
	public void setTests(Boolean tests) {
		this.tests = tests;
	}

	/**
	 * Getter for tests property
	*/
	public Boolean getTests() {
		return this.tests;
	}

	/**
	 * Setter for views property
	*/
	public void setViews(Boolean views) {
		this.views = views;
	}

	/**
	 * Getter for views property
	*/
	public Boolean getViews() {
		return this.views;
	}

	/**
	 * Setter for services property
	*/
	public void setServices(Boolean services) {
		this.services = services;
	}

	/**
	 * Getter for services property
	*/
	public Boolean getServices() {
		return this.services;
	}

	/**
	 * Setter for restServices property
	*/
	public void setRestServices(Boolean restServices) {
		this.restServices = restServices;
	}

	/**
	 * Getter for restServices property
	*/
	public Boolean getRestServices() {
		return this.restServices;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((models == null) ? 0 : models.hashCode());
		result = prime * result + ((tests == null) ? 0 : tests.hashCode());
		result = prime * result + ((views == null) ? 0 : views.hashCode());
		result = prime * result + ((services == null) ? 0 : services.hashCode());
		result = prime * result + ((restServices == null) ? 0 : restServices.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MetadataGenerate other = (MetadataGenerate)obj;
		if(models == null) {
			if(other.models != null)
				return false;
		} else if(!models.equals(other.models))
			return false;
		if(tests == null) {
			if(other.tests != null)
				return false;
		} else if(!tests.equals(other.tests))
			return false;
		if(views == null) {
			if(other.views != null)
				return false;
		} else if(!views.equals(other.views))
			return false;
		if(services == null) {
			if(other.services != null)
				return false;
		} else if(!services.equals(other.services))
			return false;
		if(restServices == null) {
			if(other.restServices != null)
				return false;
		} else if(!restServices.equals(other.restServices))
			return false;
		return true;
	}

}	// end MetadataGenerate

