//
//  MetadataClassesTransientProperty
//
//  Generated by JSON Model Generator v0.0.3 on Thu Feb 19 21:20:03 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

package com.intere.generator.metadata;

import java.util.List;
import java.util.ArrayList;
import java.util.Date;
import java.io.Serializable;


@SuppressWarnings("serial")
public class MetadataClassesTransientProperty implements Serializable {
	private String className;
	private String name;
	private String type;

	/**
	 * Setter for className property.
	 */
	public void setClassName(String className) {
		this.className = className;
	}

	/**
	 * Getter for className property.
	 */
	public String getClassName() {
		return className;
	}

	/**
	 * Setter for name property.
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Getter for name property.
	 */
	public String getName() {
		return name;
	}

	/**
	 * Setter for type property.
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * Getter for type property.
	 */
	public String getType() {
		return type;
	}

}
