//
//  MetadataClasses
//
//  Generated by JSON Model Generator v0.0.3 on Thu Feb 19 07:52:38 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

package com.intere.generator.metadata;

import java.util.List;
import java.util.ArrayList;
import java.util.Date;
import java.io.Serializable;


@SuppressWarnings("serial")
public class MetadataClasses implements Serializable {
	private String className;
	private String jsonFile;
	private String key;
	private String urlPath;
	private Boolean readonly;
	private List<MetadataClassesPropertyMap> propertyMap = new ArrayList<MetadataClassesPropertyMap>();

	/**
	 * Setter for className property.
	 */
	public void setClassName(String className) {
		this.className = className;
	}

	/**
	 * Getter for className property.
	 */
	public String getClassName() {
		return className;
	}

	/**
	 * Setter for jsonFile property.
	 */
	public void setJsonFile(String jsonFile) {
		this.jsonFile = jsonFile;
	}

	/**
	 * Getter for jsonFile property.
	 */
	public String getJsonFile() {
		return jsonFile;
	}

	/**
	 * Setter for key property.
	 */
	public void setKey(String key) {
		this.key = key;
	}

	/**
	 * Getter for key property.
	 */
	public String getKey() {
		return key;
	}

	/**
	 * Setter for urlPath property.
	 */
	public void setUrlPath(String urlPath) {
		this.urlPath = urlPath;
	}

	/**
	 * Getter for urlPath property.
	 */
	public String getUrlPath() {
		return urlPath;
	}

	/**
	 * Setter for readonly property.
	 */
	public void setReadonly(Boolean readonly) {
		this.readonly = readonly;
	}

	/**
	 * Getter for readonly property.
	 */
	public Boolean getReadonly() {
		return readonly;
	}

	/**
	 * Setter for propertyMap property.
	 */
	public void setPropertyMap(List<MetadataClassesPropertyMap> propertyMap) {
		this.propertyMap = propertyMap;
	}

	/**
	 * Getter for propertyMap property.
	 */
	public List<MetadataClassesPropertyMap> getPropertyMap() {
		return propertyMap;
	}

}
