//
//  ModelClassProperty
//
//  Generated by JSON Model Generator v0.0.3 on Wed Feb 18 08:00:03 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

package com.intere.generator.metadata;

import java.util.List;
import java.util.ArrayList;
import java.util.Date;
import java.io.Serializable;


@SuppressWarnings("serial")
public class ModelClassProperty implements Serializable {
	private String name;
	private Boolean key;
	private String type;
	private Boolean visible;
	private Boolean readonly;

	/**
	 * Setter for name property.
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Getter for name property.
	 */
	public String getName() {
		return name;
	}

	/**
	 * Setter for key property.
	 */
	public void setKey(Boolean key) {
		this.key = key;
	}

	/**
	 * Getter for key property.
	 */
	public Boolean getKey() {
		return key;
	}

	/**
	 * Setter for type property.
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * Getter for type property.
	 */
	public String getType() {
		return type;
	}

	/**
	 * Setter for visible property.
	 */
	public void setVisible(Boolean visible) {
		this.visible = visible;
	}

	/**
	 * Getter for visible property.
	 */
	public Boolean getVisible() {
		return visible;
	}

	/**
	 * Setter for readonly property.
	 */
	public void setReadonly(Boolean readonly) {
		this.readonly = readonly;
	}

	/**
	 * Getter for readonly property.
	 */
	public Boolean getReadonly() {
		return readonly;
	}

}
