package com.intere.generator.metadata;

/**
 * ModelClassRelatedClassList.java
 * 
 * Generated by JSON Model Generator v0.0.4 on Thu Apr 02 08:37:29 MDT 2015.
 * https://github.com/intere/generator-json-models
 * 
 * The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
*/

import java.io.Serializable;

@SuppressWarnings("serial")
public class ModelClassRelatedClassList implements Serializable {
	private String mapClassFrom;
	private String mapPropertyFrom;
	private String mapClassTo;
	private String mapPropertyTo;

	/**
	 * Setter for mapClassFrom property
	*/
	public void setMapClassFrom(String mapClassFrom) {
		this.mapClassFrom = mapClassFrom;
	}

	/**
	 * Getter for mapClassFrom property
	*/
	public String getMapClassFrom() {
		return this.mapClassFrom;
	}

	/**
	 * Setter for mapPropertyFrom property
	*/
	public void setMapPropertyFrom(String mapPropertyFrom) {
		this.mapPropertyFrom = mapPropertyFrom;
	}

	/**
	 * Getter for mapPropertyFrom property
	*/
	public String getMapPropertyFrom() {
		return this.mapPropertyFrom;
	}

	/**
	 * Setter for mapClassTo property
	*/
	public void setMapClassTo(String mapClassTo) {
		this.mapClassTo = mapClassTo;
	}

	/**
	 * Getter for mapClassTo property
	*/
	public String getMapClassTo() {
		return this.mapClassTo;
	}

	/**
	 * Setter for mapPropertyTo property
	*/
	public void setMapPropertyTo(String mapPropertyTo) {
		this.mapPropertyTo = mapPropertyTo;
	}

	/**
	 * Getter for mapPropertyTo property
	*/
	public String getMapPropertyTo() {
		return this.mapPropertyTo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((mapClassFrom == null) ? 0 : mapClassFrom.hashCode());
		result = prime * result + ((mapPropertyFrom == null) ? 0 : mapPropertyFrom.hashCode());
		result = prime * result + ((mapClassTo == null) ? 0 : mapClassTo.hashCode());
		result = prime * result + ((mapPropertyTo == null) ? 0 : mapPropertyTo.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ModelClassRelatedClassList other = (ModelClassRelatedClassList)obj;
		if(mapClassFrom == null) {
			if(other.mapClassFrom != null)
				return false;
		} else if(!mapClassFrom.equals(other.mapClassFrom))
			return false;
		if(mapPropertyFrom == null) {
			if(other.mapPropertyFrom != null)
				return false;
		} else if(!mapPropertyFrom.equals(other.mapPropertyFrom))
			return false;
		if(mapClassTo == null) {
			if(other.mapClassTo != null)
				return false;
		} else if(!mapClassTo.equals(other.mapClassTo))
			return false;
		if(mapPropertyTo == null) {
			if(other.mapPropertyTo != null)
				return false;
		} else if(!mapPropertyTo.equals(other.mapPropertyTo))
			return false;
		return true;
	}

}	// end ModelClassRelatedClassList

