package com.intere.generator.metadata;

/**
 * ModelClassProperty.java
 * 
 * Generated by JSON Model Generator v0.0.4 on Tue Mar 31 08:38:11 MDT 2015.
 * https://github.com/intere/generator-json-models
 * 
 * The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
*/

import java.util.ArrayList;
import org.codehaus.jackson.annotate.JsonIgnore;
import java.util.Map;
import java.util.List;
import com.intere.generator.builder.orchestration.OrchestrationDataType;
import java.io.Serializable;
import java.util.HashMap;

@SuppressWarnings("serial")
public class ModelClassProperty implements Serializable {
	private String name;
	private String value;
	private Boolean isKey;
	private String type;
	private String alias;
	private Boolean isPrimitive;
	private Boolean isTransient;
	private Boolean isVisible;
	private Boolean isReadonly;
	private Boolean isArray;
	private String arraySubType;
	private Boolean isMapped;
	private String mapClass;
	private String mapProperty;
	private String initializer;
	@JsonIgnore
	private ModelClassProperty arraySubTypeProperty;		// Transient Property
	@JsonIgnore
	private ModelClass parentModel;		// Transient Property
	@JsonIgnore
	private OrchestrationDataType dataType;		// Transient Property
	@JsonIgnore
	private ModelClass relatedClass;		// Transient Property

	/**
	 * Setter for name property
	*/
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Getter for name property
	*/
	public String getName() {
		return this.name;
	}

	/**
	 * Setter for value property
	*/
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Getter for value property
	*/
	public String getValue() {
		return this.value;
	}

	/**
	 * Setter for isKey property
	*/
	public void setIsKey(Boolean isKey) {
		this.isKey = isKey;
	}

	/**
	 * Getter for isKey property
	*/
	public Boolean getIsKey() {
		return this.isKey;
	}

	/**
	 * Setter for type property
	*/
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * Getter for type property
	*/
	public String getType() {
		return this.type;
	}

	/**
	 * Setter for alias property
	*/
	public void setAlias(String alias) {
		this.alias = alias;
	}

	/**
	 * Getter for alias property
	*/
	public String getAlias() {
		return this.alias;
	}

	/**
	 * Setter for isPrimitive property
	*/
	public void setIsPrimitive(Boolean isPrimitive) {
		this.isPrimitive = isPrimitive;
	}

	/**
	 * Getter for isPrimitive property
	*/
	public Boolean getIsPrimitive() {
		return this.isPrimitive;
	}

	/**
	 * Setter for isTransient property
	*/
	public void setIsTransient(Boolean isTransient) {
		this.isTransient = isTransient;
	}

	/**
	 * Getter for isTransient property
	*/
	public Boolean getIsTransient() {
		return this.isTransient;
	}

	/**
	 * Setter for isVisible property
	*/
	public void setIsVisible(Boolean isVisible) {
		this.isVisible = isVisible;
	}

	/**
	 * Getter for isVisible property
	*/
	public Boolean getIsVisible() {
		return this.isVisible;
	}

	/**
	 * Setter for isReadonly property
	*/
	public void setIsReadonly(Boolean isReadonly) {
		this.isReadonly = isReadonly;
	}

	/**
	 * Getter for isReadonly property
	*/
	public Boolean getIsReadonly() {
		return this.isReadonly;
	}

	/**
	 * Setter for isArray property
	*/
	public void setIsArray(Boolean isArray) {
		this.isArray = isArray;
	}

	/**
	 * Getter for isArray property
	*/
	public Boolean getIsArray() {
		return this.isArray;
	}

	/**
	 * Setter for arraySubType property
	*/
	public void setArraySubType(String arraySubType) {
		this.arraySubType = arraySubType;
	}

	/**
	 * Getter for arraySubType property
	*/
	public String getArraySubType() {
		return this.arraySubType;
	}

	/**
	 * Setter for isMapped property
	*/
	public void setIsMapped(Boolean isMapped) {
		this.isMapped = isMapped;
	}

	/**
	 * Getter for isMapped property
	*/
	public Boolean getIsMapped() {
		return this.isMapped;
	}

	/**
	 * Setter for mapClass property
	*/
	public void setMapClass(String mapClass) {
		this.mapClass = mapClass;
	}

	/**
	 * Getter for mapClass property
	*/
	public String getMapClass() {
		return this.mapClass;
	}

	/**
	 * Setter for mapProperty property
	*/
	public void setMapProperty(String mapProperty) {
		this.mapProperty = mapProperty;
	}

	/**
	 * Getter for mapProperty property
	*/
	public String getMapProperty() {
		return this.mapProperty;
	}

	/**
	 * Setter for initializer property
	*/
	public void setInitializer(String initializer) {
		this.initializer = initializer;
	}

	/**
	 * Getter for initializer property
	*/
	public String getInitializer() {
		return this.initializer;
	}

	/**
	 * Setter for arraySubTypeProperty property
	*/
	public void setArraySubTypeProperty(ModelClassProperty arraySubTypeProperty) {
		this.arraySubTypeProperty = arraySubTypeProperty;
	}

	/**
	 * Getter for arraySubTypeProperty property
	*/
	public ModelClassProperty getArraySubTypeProperty() {
		return this.arraySubTypeProperty;
	}

	/**
	 * Setter for parentModel property
	*/
	public void setParentModel(ModelClass parentModel) {
		this.parentModel = parentModel;
	}

	/**
	 * Getter for parentModel property
	*/
	public ModelClass getParentModel() {
		return this.parentModel;
	}

	/**
	 * Setter for dataType property
	*/
	public void setDataType(OrchestrationDataType dataType) {
		this.dataType = dataType;
	}

	/**
	 * Getter for dataType property
	*/
	public OrchestrationDataType getDataType() {
		return this.dataType;
	}

	/**
	 * Setter for relatedClass property
	*/
	public void setRelatedClass(ModelClass relatedClass) {
		this.relatedClass = relatedClass;
	}

	/**
	 * Getter for relatedClass property
	*/
	public ModelClass getRelatedClass() {
		return this.relatedClass;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + ((value == null) ? 0 : value.hashCode());
		result = prime * result + ((isKey == null) ? 0 : isKey.hashCode());
		result = prime * result + ((type == null) ? 0 : type.hashCode());
		result = prime * result + ((alias == null) ? 0 : alias.hashCode());
		result = prime * result + ((isPrimitive == null) ? 0 : isPrimitive.hashCode());
		result = prime * result + ((isTransient == null) ? 0 : isTransient.hashCode());
		result = prime * result + ((isVisible == null) ? 0 : isVisible.hashCode());
		result = prime * result + ((isReadonly == null) ? 0 : isReadonly.hashCode());
		result = prime * result + ((isArray == null) ? 0 : isArray.hashCode());
		result = prime * result + ((arraySubType == null) ? 0 : arraySubType.hashCode());
		result = prime * result + ((isMapped == null) ? 0 : isMapped.hashCode());
		result = prime * result + ((mapClass == null) ? 0 : mapClass.hashCode());
		result = prime * result + ((mapProperty == null) ? 0 : mapProperty.hashCode());
		result = prime * result + ((initializer == null) ? 0 : initializer.hashCode());
		result = prime * result + ((arraySubTypeProperty == null) ? 0 : arraySubTypeProperty.hashCode());
		result = prime * result + ((parentModel == null) ? 0 : parentModel.hashCode());
		result = prime * result + ((dataType == null) ? 0 : dataType.hashCode());
		result = prime * result + ((relatedClass == null) ? 0 : relatedClass.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ModelClassProperty other = (ModelClassProperty)obj;
		if(name == null) {
			if(other.name != null)
				return false;
		} else if(!name.equals(other.name))
			return false;
		if(value == null) {
			if(other.value != null)
				return false;
		} else if(!value.equals(other.value))
			return false;
		if(isKey == null) {
			if(other.isKey != null)
				return false;
		} else if(!isKey.equals(other.isKey))
			return false;
		if(type == null) {
			if(other.type != null)
				return false;
		} else if(!type.equals(other.type))
			return false;
		if(alias == null) {
			if(other.alias != null)
				return false;
		} else if(!alias.equals(other.alias))
			return false;
		if(isPrimitive == null) {
			if(other.isPrimitive != null)
				return false;
		} else if(!isPrimitive.equals(other.isPrimitive))
			return false;
		if(isTransient == null) {
			if(other.isTransient != null)
				return false;
		} else if(!isTransient.equals(other.isTransient))
			return false;
		if(isVisible == null) {
			if(other.isVisible != null)
				return false;
		} else if(!isVisible.equals(other.isVisible))
			return false;
		if(isReadonly == null) {
			if(other.isReadonly != null)
				return false;
		} else if(!isReadonly.equals(other.isReadonly))
			return false;
		if(isArray == null) {
			if(other.isArray != null)
				return false;
		} else if(!isArray.equals(other.isArray))
			return false;
		if(arraySubType == null) {
			if(other.arraySubType != null)
				return false;
		} else if(!arraySubType.equals(other.arraySubType))
			return false;
		if(isMapped == null) {
			if(other.isMapped != null)
				return false;
		} else if(!isMapped.equals(other.isMapped))
			return false;
		if(mapClass == null) {
			if(other.mapClass != null)
				return false;
		} else if(!mapClass.equals(other.mapClass))
			return false;
		if(mapProperty == null) {
			if(other.mapProperty != null)
				return false;
		} else if(!mapProperty.equals(other.mapProperty))
			return false;
		if(initializer == null) {
			if(other.initializer != null)
				return false;
		} else if(!initializer.equals(other.initializer))
			return false;
		if(arraySubTypeProperty == null) {
			if(other.arraySubTypeProperty != null)
				return false;
		} else if(!arraySubTypeProperty.equals(other.arraySubTypeProperty))
			return false;
		if(parentModel == null) {
			if(other.parentModel != null)
				return false;
		} else if(!parentModel.equals(other.parentModel))
			return false;
		if(dataType == null) {
			if(other.dataType != null)
				return false;
		} else if(!dataType.equals(other.dataType))
			return false;
		if(relatedClass == null) {
			if(other.relatedClass != null)
				return false;
		} else if(!relatedClass.equals(other.relatedClass))
			return false;
		return true;
	}

}	// end ModelClassProperty

