//
//  MetadataClassesPropertyMapTest
//
//  Generated by JSON Model Generator v0.0.3 on Mon Feb 23 08:50:21 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

package com.intere.generator.metadata;

import static org.junit.Assert.*;

import java.io.IOException;
import java.io.InputStream;

import org.codehaus.jackson.JsonParseException;
import org.codehaus.jackson.map.JsonMappingException;
import org.codehaus.jackson.map.ObjectMapper;
import org.junit.Before;
import org.junit.Test;

public class MetadataClassesPropertyMapTest {

	private static final ObjectMapper jsonMapper = new ObjectMapper();
	private MetadataClassesPropertyMap metadataClassesPropertyMap;

	@Before
	public void setUp() throws JsonParseException, JsonMappingException, IOException {
		InputStream in = getClass().getResourceAsStream("/com/intere/generator/metadata/metadata_classes_property_map.json");
		metadataClassesPropertyMap = jsonMapper.readValue(in, MetadataClassesPropertyMap.class);
	}

	@Test
	public void testProperty() {
		assertEquals("The property property didn't deserialize properly", "state", metadataClassesPropertyMap.getProperty());
	}

	@Test
	public void testMapClassName() {
		assertEquals("The mapClassName property didn't deserialize properly", "EnumerationTournamentStates", metadataClassesPropertyMap.getMapClassName());
	}

	@Test
	public void testMapClassProperty() {
		assertEquals("The mapClassProperty property didn't deserialize properly", "value", metadataClassesPropertyMap.getMapClassProperty());
	}


}
