//
//  MetadataGenerateTest
//
//  Generated by JSON Model Generator v0.0.3 on Thu Feb 19 21:20:03 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

package com.intere.generator.metadata;

import static org.junit.Assert.*;

import java.io.IOException;
import java.io.InputStream;

import org.codehaus.jackson.JsonParseException;
import org.codehaus.jackson.map.JsonMappingException;
import org.codehaus.jackson.map.ObjectMapper;
import org.junit.Before;
import org.junit.Test;

public class MetadataGenerateTest {

	private static final ObjectMapper jsonMapper = new ObjectMapper();
	private MetadataGenerate metadataGenerate;

	@Before
	public void setUp() throws JsonParseException, JsonMappingException, IOException {
		InputStream in = getClass().getResourceAsStream("/com/intere/generator/metadata/metadata_generate.json");
		metadataGenerate = jsonMapper.readValue(in, MetadataGenerate.class);
	}

	@Test
	public void testModels() {
		assertTrue("The models property didn't deserialize properly", metadataGenerate.getModels());
	}

	@Test
	public void testTests() {
		assertTrue("The tests property didn't deserialize properly", metadataGenerate.getTests());
	}

	@Test
	public void testViews() {
		assertTrue("The views property didn't deserialize properly", metadataGenerate.getViews());
	}

	@Test
	public void testServices() {
		assertTrue("The services property didn't deserialize properly", metadataGenerate.getServices());
	}

	@Test
	public void testRestServices() {
		assertTrue("The restServices property didn't deserialize properly", metadataGenerate.getRestServices());
	}


}
