//
//  MetadataClassesTransientPropertyTest
//
//  Generated by JSON Model Generator v0.0.3 on Wed Feb 25 07:37:58 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

package com.intere.generator.metadata;

import static org.junit.Assert.*;

import java.io.IOException;
import java.io.InputStream;

import org.codehaus.jackson.JsonParseException;
import org.codehaus.jackson.map.JsonMappingException;
import org.codehaus.jackson.map.ObjectMapper;
import org.junit.Before;
import org.junit.Test;

public class MetadataClassesTransientPropertyTest {

	private static final ObjectMapper jsonMapper = new ObjectMapper();
	private MetadataClassesTransientProperty metadataClassesTransientProperty;

	@Before
	public void setUp() throws JsonParseException, JsonMappingException, IOException {
		InputStream in = getClass().getResourceAsStream("/com/intere/generator/metadata/metadata_classes_transient_property.json");
		metadataClassesTransientProperty = jsonMapper.readValue(in, MetadataClassesTransientProperty.class);
	}

	@Test
	public void testClassName() {
		assertEquals("The className property didn't deserialize properly", "", metadataClassesTransientProperty.getClassName());
	}

	@Test
	public void testName() {
		assertEquals("The name property didn't deserialize properly", "", metadataClassesTransientProperty.getName());
	}

	@Test
	public void testType() {
		assertEquals("The type property didn't deserialize properly", "", metadataClassesTransientProperty.getType());
	}


}
