package com.intere.generator.metadata;

/**
 * MetadataGenerateTest.java
 * 
 * Generated by JSON Model Generator v0.0.3 on Wed Mar 11 06:37:40 MDT 2015.
 * https://github.com/intere/generator-json-models
 * 
 * The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
*/

import static org.junit.Assert.*;

import org.junit.Test;
import org.junit.Before;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import org.codehaus.jackson.JsonGenerationException;
import org.codehaus.jackson.JsonParseException;
import org.codehaus.jackson.map.JsonMappingException;
import org.codehaus.jackson.map.ObjectMapper;


public class MetadataGenerateTest {
	private static final ObjectMapper jsonMapper = new ObjectMapper();
	private MetadataGenerate instance;

	@Before
	public void setUp() throws JsonParseException, JsonMappingException, IOException {
		InputStream in = new ByteArrayInputStream("{}".getBytes());
		instance = jsonMapper.readValue(in, MetadataGenerate.class);
	}

	protected String serialize(MetadataGenerate object)  throws JsonGenerationException, JsonMappingException, IOException {
		return jsonMapper.writeValueAsString(object);
	}

	protected MetadataGenerate deserialize(String json) throws JsonParseException, JsonMappingException, IOException {
		return jsonMapper.readValue(json, MetadataGenerate.class);
	}

	@Test
	public void testModels() throws Exception {
		final Boolean expected = true;
		instance.setModels(expected);
		String serialized = serialize(instance);
		instance = deserialize(serialized);
		assertEquals("The models property didn't deserialize properly", expected, instance.getModels());
	}

	@Test
	public void testTests() throws Exception {
		final Boolean expected = true;
		instance.setTests(expected);
		String serialized = serialize(instance);
		instance = deserialize(serialized);
		assertEquals("The tests property didn't deserialize properly", expected, instance.getTests());
	}

	@Test
	public void testViews() throws Exception {
		final Boolean expected = true;
		instance.setViews(expected);
		String serialized = serialize(instance);
		instance = deserialize(serialized);
		assertEquals("The views property didn't deserialize properly", expected, instance.getViews());
	}

	@Test
	public void testServices() throws Exception {
		final Boolean expected = true;
		instance.setServices(expected);
		String serialized = serialize(instance);
		instance = deserialize(serialized);
		assertEquals("The services property didn't deserialize properly", expected, instance.getServices());
	}

	@Test
	public void testRestServices() throws Exception {
		final Boolean expected = true;
		instance.setRestServices(expected);
		String serialized = serialize(instance);
		instance = deserialize(serialized);
		assertEquals("The restServices property didn't deserialize properly", expected, instance.getRestServices());
	}

}	// end MetadataGenerateTest

