//
//  MetadataTest
//
//  Generated by JSON Model Generator v0.0.3 on Thu Feb 19 07:52:38 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

package com.intere.generator.metadata;

import static org.junit.Assert.*;

import java.io.IOException;
import java.io.InputStream;

import org.codehaus.jackson.JsonParseException;
import org.codehaus.jackson.map.JsonMappingException;
import org.codehaus.jackson.map.ObjectMapper;
import org.junit.Before;
import org.junit.Test;

public class MetadataTest {

	private static final ObjectMapper jsonMapper = new ObjectMapper();
	private Metadata metadata;

	@Before
	public void setUp() throws JsonParseException, JsonMappingException, IOException {
		InputStream in = getClass().getResourceAsStream("/com/intere/generator/metadata/metadata.json");
		metadata = jsonMapper.readValue(in, Metadata.class);
	}

	@Test
	public void testLanguage() {
		assertEquals("The language property didn't deserialize properly", "objective-c", metadata.getLanguage());
	}

	@Test
	public void testNamespace() {
		// TODO (don't know how to handle null)
	}

	@Test
	public void testClasses() {
		// TODO: See Metadata
		// TODO: See Metadata
	}

	@Test
	public void testGenerate() {
		// TODO: See Metadata
	}


}
