package com.intere.generator.metadata;

/**
 * ModelClassRelatedClassListTest.java
 * 
 * Generated by JSON Model Generator v0.0.4 on Thu Apr 02 08:37:30 MDT 2015.
 * https://github.com/intere/generator-json-models
 * 
 * The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
*/

import static org.junit.Assert.*;

import org.junit.Test;
import org.junit.Before;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import org.codehaus.jackson.JsonGenerationException;
import org.codehaus.jackson.JsonParseException;
import org.codehaus.jackson.map.JsonMappingException;
import org.codehaus.jackson.map.ObjectMapper;


public class ModelClassRelatedClassListTest {
	private static final ObjectMapper jsonMapper = new ObjectMapper();
	private ModelClassRelatedClassList instance;

	@Before
	public void setUp() throws JsonParseException, JsonMappingException, IOException {
		InputStream in = new ByteArrayInputStream("{}".getBytes());
		instance = jsonMapper.readValue(in, ModelClassRelatedClassList.class);
	}

	protected String serialize(ModelClassRelatedClassList object)  throws JsonGenerationException, JsonMappingException, IOException {
		return jsonMapper.writeValueAsString(object);
	}

	protected ModelClassRelatedClassList deserialize(String json) throws JsonParseException, JsonMappingException, IOException {
		return jsonMapper.readValue(json, ModelClassRelatedClassList.class);
	}

	@Test
	public void testMapClassFrom() throws Exception {
		final String expected = "test";
		instance.setMapClassFrom(expected);
		String serialized = serialize(instance);
		instance = deserialize(serialized);
		assertEquals("The mapClassFrom property didn't deserialize properly", expected, instance.getMapClassFrom());
	}

	@Test
	public void testMapPropertyFrom() throws Exception {
		final String expected = "test";
		instance.setMapPropertyFrom(expected);
		String serialized = serialize(instance);
		instance = deserialize(serialized);
		assertEquals("The mapPropertyFrom property didn't deserialize properly", expected, instance.getMapPropertyFrom());
	}

	@Test
	public void testMapClassTo() throws Exception {
		final String expected = "test";
		instance.setMapClassTo(expected);
		String serialized = serialize(instance);
		instance = deserialize(serialized);
		assertEquals("The mapClassTo property didn't deserialize properly", expected, instance.getMapClassTo());
	}

	@Test
	public void testMapPropertyTo() throws Exception {
		final String expected = "test";
		instance.setMapPropertyTo(expected);
		String serialized = serialize(instance);
		instance = deserialize(serialized);
		assertEquals("The mapPropertyTo property didn't deserialize properly", expected, instance.getMapPropertyTo());
	}

}	// end ModelClassRelatedClassListTest

