//
//  ModelClassTest
//
//  Generated by JSON Model Generator v0.0.3 on Wed Feb 25 07:38:00 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

package com.intere.generator.metadata;

import static org.junit.Assert.*;

import java.io.IOException;
import java.io.InputStream;

import org.codehaus.jackson.JsonParseException;
import org.codehaus.jackson.map.JsonMappingException;
import org.codehaus.jackson.map.ObjectMapper;
import org.junit.Before;
import org.junit.Test;

public class ModelClassTest {

	private static final ObjectMapper jsonMapper = new ObjectMapper();
	private ModelClass modelClass;

	@Before
	public void setUp() throws JsonParseException, JsonMappingException, IOException {
		InputStream in = getClass().getResourceAsStream("/com/intere/generator/metadata/model_class.json");
		modelClass = jsonMapper.readValue(in, ModelClass.class);
	}

	@Test
	public void testUniqueId() {
		assertEquals("The uniqueId property didn't deserialize properly", "ou812", modelClass.getUniqueId());
	}

	@Test
	public void testClassName() {
		assertEquals("The className property didn't deserialize properly", "Contest", modelClass.getClassName());
	}

	@Test
	public void testFileName() {
		assertEquals("The fileName property didn't deserialize properly", "Contest.java", modelClass.getFileName());
	}

	@Test
	public void testTestClassName() {
		assertEquals("The testClassName property didn't deserialize properly", "ContestTest", modelClass.getTestClassName());
	}

	@Test
	public void testReadonly() {
		assertFalse("The readonly property didn't deserialize properly", modelClass.getReadonly());
	}

	@Test
	public void testNamespace() {
		assertEquals("The namespace property didn't deserialize properly", "com.intere.generated", modelClass.getNamespace());
	}

	@Test
	public void testHasSubClasses() {
		assertTrue("The hasSubClasses property didn't deserialize properly", modelClass.getHasSubClasses());
	}

	@Test
	public void testProperty() {
		// TODO: See ModelClass
	}

	@Test
	public void testRestUrl() {
		assertEquals("The restUrl property didn't deserialize properly", "/contest", modelClass.getRestUrl());
	}

	@Test
	public void testImports() {
		assertEquals("The imports property at index 0 didn't deserialize properly", "Enumeration", modelClass.getImports().get(0));
	}


}
