//
//  ModelClassPropertyTest
//
//  Generated by JSON Model Generator v0.0.3 on Wed Feb 25 07:38:00 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

package com.intere.generator.metadata;

import static org.junit.Assert.*;

import java.io.IOException;
import java.io.InputStream;

import org.codehaus.jackson.JsonParseException;
import org.codehaus.jackson.map.JsonMappingException;
import org.codehaus.jackson.map.ObjectMapper;
import org.junit.Before;
import org.junit.Test;

public class ModelClassPropertyTest {

	private static final ObjectMapper jsonMapper = new ObjectMapper();
	private ModelClassProperty modelClassProperty;

	@Before
	public void setUp() throws JsonParseException, JsonMappingException, IOException {
		InputStream in = getClass().getResourceAsStream("/com/intere/generator/metadata/model_class_property.json");
		modelClassProperty = jsonMapper.readValue(in, ModelClassProperty.class);
	}

	@Test
	public void testName() {
		assertEquals("The name property didn't deserialize properly", "id", modelClassProperty.getName());
	}

	@Test
	public void testIsKey() {
		assertTrue("The isKey property didn't deserialize properly", modelClassProperty.getIsKey());
	}

	@Test
	public void testType() {
		assertEquals("The type property didn't deserialize properly", "String", modelClassProperty.getType());
	}

	@Test
	public void testIsPrimitive() {
		assertFalse("The isPrimitive property didn't deserialize properly", modelClassProperty.getIsPrimitive());
	}

	@Test
	public void testIsTransient() {
		assertFalse("The isTransient property didn't deserialize properly", modelClassProperty.getIsTransient());
	}

	@Test
	public void testIsVisible() {
		assertTrue("The isVisible property didn't deserialize properly", modelClassProperty.getIsVisible());
	}

	@Test
	public void testIsReadonly() {
		assertTrue("The isReadonly property didn't deserialize properly", modelClassProperty.getIsReadonly());
	}

	@Test
	public void testIsArray() {
		assertTrue("The isArray property didn't deserialize properly", modelClassProperty.getIsArray());
	}

	@Test
	public void testArraySubType() {
		assertEquals("The arraySubType property didn't deserialize properly", "String", modelClassProperty.getArraySubType());
	}


}
