package com.intere.generator.builder.generation.utils;

import java.util.Date;

import com.intere.generator.App;

public class CodeGenerationUtils {
	public static String generateCStyleHeaderBlock(String filename) {
		return "//\n" +
				"//  " + filename + "\n" +
				"//\n" +
				"//  Generated by JSON Model Generator v" + App.getVersion() + " on " + getDate() + ".\n" +
				"//    https://github.com/intere/generator-json-models\n" +
				"//\n" +
				"//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content\n" +
				"//\n" +
				"//\n\n";
	}
	
	public static String getDate() {
		return new Date().toString();
	}
}
