package com.intere.generator.builder.generation;

import static com.intere.generator.deserializer.JsonNodeUtils.*;

import java.util.Iterator;

import org.codehaus.jackson.JsonNode;

import com.intere.generator.App;
import com.intere.generator.builder.interpreter.JavaInterpreter;
import com.intere.generator.builder.interpreter.JsonLanguageInterpreter;
import com.intere.generator.deserializer.JsonDeserializer;

public class JavaGeneration extends CodeGeneration {

	@Override
	public String generateHeaderFile(JsonDeserializer deserializer) {
		return null;	// Java doesn't have header files
	}

	private String buildGettersAndSetters(JsonNode node, String className, String name) {
		String propName = getInterpreter().cleanVariableName(name);
		String propType = getNodeType(node, className, name);
		String getSetName = getInterpreter().buildGetterAndSetterName(name);

		if(propType.length()>0) {
			return "\t/**\n" +
				"\t * Setter for " + propName + " property.\n" +
				"\t */\n" +
				"\tpublic void set" + getSetName + "(" + propType + " " + propName + ") {\n" +
				"\t\tthis." + propName + " = " + propName + ";\n" +
				"\t}\n\n" +
				"\t/**\n" +
				"\t * Getter for " + propName + " property.\n" +
				"\t */\n" +
				"\tpublic " + propType + " get" + getSetName + "() {\n" +
				"\t\treturn " + propName + ";\n" +
				"\t}\n\n";
		}
		return "";
	}

	public String buildPropertyDeclaration(JsonNode node, String className, String name) {
		String propName = getInterpreter().cleanVariableName(name);
		String nodeType = getNodeType(node, className, name);
		if(nodeType.length()>0) {
			return "private " + nodeType + " " + propName + ";\n";
		}
		
		return "";
	}

	public String getNodeType(JsonNode node, String className, String name) {
		String subClass = getInterpreter().buildSubClassName(className, name);
		if(isText(node)) {
			return "String";
		} else if(isDate(node)) {
			return "Date";
		} else if(isInteger(node) || isLong(node)) {
			return "Long";
		} else if(isFloat(node)) {
			return "Double";
		} else if(isBoolean(node)) {
			return "Boolean";
		} else if(isObject(node)) {
			return subClass;
		} else if(isArrayOfObjects(node)) {
			return "List<" + getNodeType(node.iterator().next(), className, name) + ">";
		} else if(isArrayofArrays(node)) {
			return "List<List>";
		} else if(isArray(node)) {
			if(node.size()>0) {
				return "List<" + getNodeType(node.get(0), className, name) + ">";
			}
			return "List";
		} else {
			System.out.println("Unknown Node type: " + node.toString() + ", defaulting to String");
			return "String";
		}
	}

	@Override
	public String generateImplementationFile(JsonDeserializer deserializer) {
		String className = deserializer.getName();
		String filename = getInterpreter().buildFilenameFromClassname(className);
		String packageName = deserializer.getNamespace();
		JsonNode node = deserializer.getNode();

		StringBuilder builder = new StringBuilder();
		builder.append("/*\n" +
				" *  " + filename + ".java\n" +
				" *  Generated by JSON Model Generator v" + App.getVersion() + " on " + getDate() + ".\n" +
				" *    https://github.com/intere/generator-json-models\n" +
				" *\n" +
				" *    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content\n" +
				" *\n" +
				" */\n\n");
		builder.append("package " + packageName + ";\n\n");
		builder.append("import java.util.List;\n" +
				"import java.util.Date;\n" +
				"import java.io.Serializable;\n");

		builder.append("\n\n@SuppressWarnings(\"serial\")\n" + 
				"public class " + className + " implements Serializable {\n");

		Iterator<String> iter = node.getFieldNames();
		while(iter.hasNext()) {
			String name = iter.next();
			String declaration = buildPropertyDeclaration(node.get(name), className, name);
			if(declaration.length()>0) {
				builder.append("\t" + declaration);
			}
		}

		builder.append("\n");

		iter = node.getFieldNames();
		while(iter.hasNext()) {
			String name = iter.next();
			builder.append(buildGettersAndSetters(node.get(name), className, name));
		}

		builder.append("}\n");

		return builder.toString();
	}
	
	@Override
	public String generateTestFile(JsonDeserializer deserializer, String jsonFilename, String jsonTestFilename) {
		String className = deserializer.getName();
		String testClassName = deserializer.getTestFilename();
		JsonNode node = deserializer.getNode();
		String jsonExtension = getExtensionFromFilename(jsonFilename);
		
		return "";
	}

	@Override
	public JsonLanguageInterpreter getInterpreter() {
		return new JavaInterpreter();
	}
}
