#
# enumeration.rb
# 
# Generated by JSON Model Generator v0.0.3 on Mon Mar 09 07:57:46 MDT 2015.
# https://github.com/intere/generator-json-models
# 
# The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
#

class Enumeration < JsonModel
	def purse_types
		@purse_types ||= json.try(:[], :purseTypes).map {|o| EnumerationPurseTypes.new(purseTypes)}
	end

	def skill_levels
		@skill_levels ||= json.try(:[], :skillLevels).map {|o| EnumerationSkillLevels.new(skillLevels)}
	end

	def tournament_sizes
		@tournament_sizes ||= json.try(:[], :tournamentSizes).map {|o| EnumerationTournamentSizes.new(tournamentSizes)}
	end

	def tournament_states
		@tournament_states ||= json.try(:[], :tournamentStates).map {|o| EnumerationTournamentStates.new(tournamentStates)}
	end

	def tournament_types
		@tournament_types ||= json.try(:[], :tournamentTypes).map {|o| EnumerationTournamentTypes.new(tournamentTypes)}
	end

	def user_types
		@user_types ||= json.try(:[], :userTypes).map {|o| EnumerationUserTypes.new(userTypes)}
	end


end		# End of Enumeration

