#
# enumeration.rb
#
# Generated by JSON Model Generator v0.0.5 on Aug 28, 2016
# https://github.com/intere/generator-json-models
#
# The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
#

class Enumeration

    def purse_types
        @purse_types ||= json.try(:[], :purseTypes).map {|o| EnumerationPurseTypes.new(o)}
    end

    def skill_levels
        @skill_levels ||= json.try(:[], :skillLevels).map {|o| EnumerationSkillLevels.new(o)}
    end

    def tournament_sizes
        @tournament_sizes ||= json.try(:[], :tournamentSizes).map {|o| EnumerationTournamentSizes.new(o)}
    end

    def tournament_states
        @tournament_states ||= json.try(:[], :tournamentStates).map {|o| EnumerationTournamentStates.new(o)}
    end

    def tournament_types
        @tournament_types ||= json.try(:[], :tournamentTypes).map {|o| EnumerationTournamentTypes.new(o)}
    end

    def user_types
        @user_types ||= json.try(:[], :userTypes).map {|o| EnumerationUserTypes.new(o)}
    end


    def initialize(init_json)
        if init_json.class == String
            @json = JSON.parse(init_json)
        else
            @json = init_json
        end
        @json.symbolize_keys!
    end

    def json
        @json
    end
end
