#
# enumeration_user_types.rb
# 
# Generated by JSON Model Generator v0.0.3 on Wed Mar 04 20:22:53 MST 2015.
# https://github.com/intere/generator-json-models
# 
# The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
#

class EnumerationUserTypes < JsonModel
	def name
		json.try(:[], :name)
	end

	def value
		json.try(:[], :value)
	end


end		# End of EnumerationUserTypes

