#
# enumeration_purse_types.rb
# 
# Generated by JSON Model Generator v0.0.3 on Mon Mar 02 07:35:40 MST 2015.
# https://github.com/intere/generator-json-models
# 
# The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
#

class EnumerationPurseTypes < JsonModel
	def title
		@json.try(:[], 'title')
	end


end		# End of EnumerationPurseTypes

