#
# enumeration_tournament_states.rb
# 
# Generated by JSON Model Generator v0.0.4 on Fri Mar 20 08:22:20 MDT 2015.
# https://github.com/intere/generator-json-models
# 
# The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
#

class EnumerationTournamentStates < JsonModel
	def name
		json.try(:[], :name)
	end

	def value
		json.try(:[], :value)
	end


end		# End of EnumerationTournamentStates

