#
# enumeration_tournament_types.rb
# 
# Generated by JSON Model Generator v0.0.3 on Sun Mar 15 08:44:00 MDT 2015.
# https://github.com/intere/generator-json-models
# 
# The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
#

class EnumerationTournamentTypes < JsonModel
	def name
		json.try(:[], :name)
	end

	def value
		json.try(:[], :value)
	end


end		# End of EnumerationTournamentTypes

