#
# enumeration_skill_levels.rb
# 
# Generated by JSON Model Generator v0.0.4 on Tue Mar 24 07:59:17 MDT 2015.
# https://github.com/intere/generator-json-models
# 
# The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
#

class EnumerationSkillLevels < JsonModel
	def description
		json.try(:[], :description)
	end

	def image
		json.try(:[], :image)
	end

	def name
		json.try(:[], :name)
	end

	def value
		json.try(:[], :value)
	end


end		# End of EnumerationSkillLevels

