#
# enumeration_tournament_sizes.rb
#
# Generated by JSON Model Generator v0.0.4 on Aug 28, 2016
# https://github.com/intere/generator-json-models
#
# The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
#

class EnumerationTournamentSizes

    def name
        @name ||= json.try(:[], :name)
    end

    def size
        @size ||= json.try(:[], :size)
    end


    def initialize(init_json)
        if init_json.class == String
            @json = JSON.parse(init_json)
        else
            @json = init_json
        end
        @json.symbolize_keys!
    end

    def json
        @json
    end
end
