#
# enumeration_tournament_sizes.rb
# 
# Generated by JSON Model Generator v0.0.3 on Tue Mar 03 07:53:23 MST 2015.
# https://github.com/intere/generator-json-models
# 
# The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
#

class EnumerationTournamentSizes < JsonModel
	def name
		json.try(:[], :name)
	end

	def size
		json.try(:[], :size)
	end


end		# End of EnumerationTournamentSizes

